// Generate the Yahoo bridge userscript from the SAME sources as the standalone
// tool: shell CSS + shell body + players.json + engine + bridge reader.
//
// There is deliberately no second copy of the UI or the engine. If the two
// builds could drift, the one you tested would not be the one you drafted with.
//
//   node tool/make_userscript.js <sha256-of-sources>
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const stamp = process.argv[2];
if (!stamp) { console.error('make_userscript: missing source hash'); process.exit(1); }

const shell = fs.readFileSync(path.join(ROOT, 'tool/shell_html.txt'), 'utf8');
const players = fs.readFileSync(path.join(ROOT, 'data/players.json'), 'utf8');
const engineRaw = fs.readFileSync(path.join(ROOT, 'tool/engine_js.txt'), 'utf8');
const bridge = fs.readFileSync(path.join(ROOT, 'tool/yahoo_bridge_js.txt'), 'utf8');

// CSS between <style> and </style>.
const css = shell.split('<style>')[1].split('</style>')[0];
// Body markup: the .wrap div plus the footer, i.e. everything between <body>
// and the opening <script>.
const body = shell.split('<body>')[1].split('<script>')[0];
// The engine file ends with the page's closing tags; the userscript needs only
// the JavaScript.
const engine = engineRaw.split('</script>')[0];

if (!css.trim() || !body.trim() || !engine.trim()) {
  console.error('make_userscript: failed to slice a source (css/body/engine empty)');
  process.exit(1);
}

const out = `// ==UserScript==
// @name         SSTLV Live Draft Assistant — Yahoo board bridge
// @namespace    sstlv.draft
// @version      ${stamp.slice(0, 12)}
// @description  Reads the live Yahoo draft board and runs the draft assistant over it. No player names typed.
// @match        https://football.fantasysports.yahoo.com/*
// @match        https://*.fantasysports.yahoo.com/*
// @run-at       document-idle
// @grant        none
// @noframes
// ==/UserScript==
//
// Built from the same sources as tool/live-draft-assistant.html.
// Source hash: sha256:${stamp}
// Do not edit this file — edit the sources and run ./build.sh.

(function () {
  "use strict";
  if (window.__sstlvBridge) return;      // survive Yahoo's soft navigations
  window.__sstlvBridge = true;

  // The panel lives in a shadow root: Yahoo's stylesheet cannot reach in and
  // restyle it, our ids cannot collide with theirs, and the engine's $() works
  // unchanged because ShadowRoot implements getElementById.
  var HOST = document.createElement("div");
  HOST.id = "sstlv-host";
  HOST.style.cssText = [
    "position:fixed", "top:0", "right:0", "width:400px", "max-width:96vw",
    "height:100vh", "z-index:2147483645", "overflow:auto",
    "box-shadow:-2px 0 18px rgba(0,0,0,.45)", "font-size:15px"
  ].join(";");
  var SHADOW = HOST.attachShadow({ mode: "open" });
  SHADOW.innerHTML = "<style>" + ${JSON.stringify(css)} + "</style>" +
    ${JSON.stringify(body)};
  document.documentElement.appendChild(HOST);

  // A collapse tab, because this sits on top of the draft room.
  var TAB = document.createElement("button");
  TAB.textContent = "SSTLV";
  TAB.style.cssText = [
    "position:fixed", "top:8px", "right:8px", "z-index:2147483646",
    "background:#F5C518", "color:#0D1015", "border:0", "border-radius:5px",
    "font:700 11px ui-monospace,Menlo,Consolas,monospace", "letter-spacing:.09em",
    "padding:7px 10px", "cursor:pointer"
  ].join(";");
  TAB.onclick = function () {
    var hidden = HOST.style.display === "none";
    HOST.style.display = hidden ? "" : "none";
    TAB.style.right = hidden ? "8px" : "8px";
  };
  document.documentElement.appendChild(TAB);

  // Tell the engine to render into the shadow root instead of the document.
  var UIROOT_OVERRIDE = SHADOW;

  const PLAYERS = ${players.trim()};
  var BUILD_STAMP = "sha256:${stamp}";

${engine}

${bridge}
})();
`;

const dest = path.join(ROOT, 'tool/yahoo-draft-bridge.user.js');
fs.writeFileSync(dest, out);
console.log('  userscript -> tool/yahoo-draft-bridge.user.js (' + out.length + ' bytes)');
